/**
 * MarvinAstro against what Marvin actually publishes.
 *
 * `tests/fixtures/core-embeds.json` is generated by Marvin's own publishing code
 * (`media_embeds.publish.build_embed` / `site_embeds`, feat/media-embeds) for both embed modes:
 * YouTube (titled, with quotes and angle brackets), YouTube Shorts, Vimeo, Spotify track /
 * playlist / episode, an unavailable video and a Bandcamp link card. Regenerate it with
 * `tests/fixtures/core-embeds.gen.py` when the published shape changes.
 */
import { readFileSync } from 'node:fs';
import { experimental_AstroContainer as AstroContainer } from 'astro/container';
import { JSDOM } from 'jsdom';
import { beforeAll, describe, expect, it } from 'vitest';
import Embed from '../../src/components/Embed.astro';
import { installEmbedLoader } from '../../src/components/embed-frame.js';
import { entryEmbeds, siteEmbeds, type MarvinEmbed, type MarvinSiteEmbeds } from '../../src/embeds.js';
import { createFieldAccessor } from '../../src/fields.js';
import { createMarkdownRenderer } from '../../src/markdown.js';
import type { MarvinContentEntry } from '../../src/types.js';
import fixtures from '../fixtures/core-embeds.json';

type Mode = 'click_to_load' | 'direct';
const MODES: Mode[] = ['click_to_load', 'direct'];
const site = fixtures.site as Record<Mode, MarvinSiteEmbeds>;
const embeds = fixtures.embeds as unknown as Record<Mode, Record<string, MarvinEmbed>>;
const facades = Object.entries(embeds.click_to_load).filter(([, e]) => e.status === 'ok');
/** `entry.embeds` as core publishes it: keyed by the URL as written. */
const byUrl = (mode: Mode) =>
  Object.fromEntries(Object.values(embeds[mode]).map((embed) => [embed.url, embed]));

/** Parse an HTML fragment. jsdom's getAttribute undoes the `&quot;` escaping, as a browser does. */
function fragment(html: string) {
  const dom = new JSDOM(`<!doctype html><body>${html}</body>`);
  return { dom, body: dom.window.document.body };
}

type Node = { tag: string; attrs: Record<string, unknown>; children: (Node | string)[] };

/** A comparable tree: decoded attributes (JSON ones parsed, styles unspaced) and trimmed text. */
function tree(element: Element): Node {
  const attrs: Record<string, unknown> = {};
  for (const { name, value } of Array.from(element.attributes)) {
    if (name === 'data-marvin-embed-attrs' || name === 'data-marvin-embed-hosts') {
      attrs[name] = JSON.parse(value);
    } else if (name === 'style') {
      attrs[name] = value.replace(/\s+/g, '');
    } else {
      attrs[name] = value;
    }
  }
  const children: (Node | string)[] = [];
  for (const child of Array.from(element.childNodes)) {
    if (child.nodeType === 1) children.push(tree(child as Element));
    else if (child.nodeType === 3 && child.textContent!.trim()) {
      children.push(child.textContent!.replace(/\s+/g, ' ').trim());
    }
  }
  return { tag: element.tagName.toLowerCase(), attrs, children };
}

function only(html: string): Element {
  const { body } = fragment(html);
  expect(body.children).toHaveLength(1);
  return body.children[0];
}

let container: AstroContainer;
beforeAll(async () => {
  container = await AstroContainer.create();
});

describe('core fixtures', () => {
  it('cover both modes, every kind, and the null-not-omitted optional fields', () => {
    const all = Object.values(embeds.click_to_load);
    expect(new Set(all.map((e) => e.kind))).toEqual(new Set(['video', 'audio', 'playlist', 'podcast']));
    expect(new Set(all.map((e) => e.status))).toEqual(new Set(['ok', 'unavailable', 'link']));
    expect(embeds.click_to_load.vimeo.title).toBeNull();
    expect(embeds.click_to_load.vimeo.iframe?.height).toBeNull();
    expect(embeds.click_to_load.spotify_track.iframe?.aspectRatio).toBeNull();
    expect(embeds.click_to_load.youtube_shorts.iframe?.aspectRatio).toBe('9/16');
    expect(embeds.click_to_load.spotify_playlist.kind).toBe('playlist');
    expect(embeds.click_to_load.spotify_episode.kind).toBe('podcast');
    expect(embeds.click_to_load.bandcamp_link.iframe).toBeNull();
  });

  it('siteEmbeds() passes core’s site.embeds through unchanged', () => {
    for (const mode of MODES) expect(siteEmbeds(site[mode])).toEqual(site[mode]);
  });
});

describe('<Embed> renders the same markup as core’s html', () => {
  for (const mode of MODES) {
    for (const [name, embed] of Object.entries(embeds[mode])) {
      it(`${mode} / ${name}`, async () => {
        const ours = await container.renderToString(Embed, {
          props: { embed, mode, consentText: site[mode].consentText },
        });

        expect(tree(only(ours))).toEqual(tree(only(embed.html)));
      });
    }
  }
});

describe('the loader on core’s facades', () => {
  for (const [name, facade] of facades) {
    it(`${name}: click builds the same iframe core renders in direct mode`, () => {
      const { dom, body } = fragment(facade.html);
      const document = dom.window.document;
      installEmbedLoader(document);

      // Click the title span: a real click lands on a child, and the listener is delegated.
      const title = body.querySelector('.marvin-embed__title')!;
      title.dispatchEvent(new dom.window.MouseEvent('click', { bubbles: true }));

      const figure = body.querySelector('figure')!;
      const iframe = figure.querySelector('iframe')!;
      expect(iframe).not.toBeNull();
      expect(figure.querySelector('button')).toBeNull();
      expect(figure.classList.contains('marvin-embed--loaded')).toBe(true);
      expect(figure.querySelector('a.marvin-embed__link')).not.toBeNull();
      expect(document.activeElement).toBe(iframe);

      const direct = only(embeds.direct[name].html).querySelector('iframe')!;
      expect(tree(iframe).attrs).toEqual(tree(direct).attrs);
    });
  }

  it('refuses a core facade whose src was swapped for another host', () => {
    const tampered = facades[0][1].html.replaceAll(
      'https://www.youtube-nocookie.com/embed/',
      'https://evil.example/embed/'
    );
    const { dom, body } = fragment(tampered);
    installEmbedLoader(dom.window.document);
    body.querySelector('button')!.click();

    expect(body.querySelector('iframe')).toBeNull();
    expect(body.querySelector('button')!.disabled).toBe(true);
    expect(body.querySelector('figure')!.classList.contains('marvin-embed--blocked')).toBe(true);
  });

  it('is keyboard reachable: the facade is a real button', () => {
    for (const [, facade] of facades) {
      const button = only(facade.html).querySelector('button')!;
      expect(button.getAttribute('type')).toBe('button');
    }
  });
});

describe('markdown and fields with core embeds', () => {
  const render = createMarkdownRenderer();

  for (const mode of MODES) {
    it(`renders every bare embedded URL as core’s ${mode} html, verbatim`, async () => {
      for (const embed of Object.values(embeds[mode])) {
        const html = await render(`Before.\n\n${embed.url}\n\nAfter.`, { embeds: byUrl(mode) });
        expect(html, embed.url).toContain(embed.html);
      }
    });
  }

  it('f.embed() returns core’s embed, null fields and all', () => {
    const entry = {
      data: { video: embeds.click_to_load.vimeo.url },
      embeds: byUrl('click_to_load'),
    } as unknown as MarvinContentEntry;
    const f = createFieldAccessor(entry, { renderMarkdown: render });

    expect(f.embed('video')).toEqual(embeds.click_to_load.vimeo);
    expect(f.embed('video')?.title).toBeNull();
  });

  it('an entry with core’s empty embeds object has none', () => {
    expect(entryEmbeds({ embeds: {} })).toBeUndefined();
  });
});

describe('embeds.css covers core’s markup', () => {
  const css = readFileSync(new URL('../../src/components/embeds.css', import.meta.url), 'utf8');

  it('has a rule for every class core emits', () => {
    const classes = new Set<string>();
    for (const mode of MODES) {
      for (const embed of Object.values(embeds[mode])) {
        for (const element of Array.from(fragment(embed.html).body.querySelectorAll('[class]'))) {
          for (const name of Array.from(element.classList)) classes.add(name);
        }
      }
    }
    // Kind modifiers are styled only where a kind needs its own sizing.
    const unstyled = new Set(['marvin-embed--video', 'marvin-embed--playlist', 'marvin-embed--facade']);
    for (const name of classes) {
      if (unstyled.has(name)) continue;
      expect(css, name).toContain(`.${name}`);
    }
  });

  it('reads the sizing properties core sets on the figure', () => {
    expect(css).toContain('var(--marvin-embed-aspect');
    expect(css).toContain('var(--marvin-embed-height');
  });
});
